channels:
  - defaults
  - conda-forge  # Additional channel, you can add more if needed
dependencies:
  - python=3.10
  - gymnasium=0.28.1
  - numpy=1.26.0
  - pre-commit
  - pylint
  - pydantic
  - pytest
