name: Python application

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: create conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: furnace
          channels: defaults,conda-forge
          environment-file: environment.yaml
          auto-activate-base: false
      - name: Install dependencies
        run: conda install --name furnace --file environment.yaml
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Test with pytest
        run: |
          pytest
